function getVideo (exercise) {
  const ex = Object.keys(videos).find((v) => v.includes(exercise.trim()))
  return videos[ex]
}

const videos = {
  'Supino Reto Barra': 'https://www.youtube.com/watch?v=R8P8ltM6R8s',
  'Supino Reto Halteres': 'https://www.youtube.com/watch?v=l4ffhu6yvPU',
  'Supino Reto Smith': 'https://www.youtube.com/watch?v=UAb55wYcN_c',
  'Supino Inclinado Barra': 'https://www.youtube.com/watch?v=Yc7AsFlGfwo',
  'Supino Inclinado Halteres': 'https://www.youtube.com/watch?v=YxqVHg6bQkU',
  'Supino Inclinado Smith': 'https://www.youtube.com/watch?v=rJw0dnJpco4',
  'Supino Declinado Barra': 'https://www.youtube.com/watch?v=ggKx-LVc_RM',
  'Supino Declinado Halteres': 'https://www.youtube.com/watch?v=sZnFT0BwYH4',
  'Supino Declinado Smith': 'https://www.youtube.com/watch?v=KWe0--rR4Ig',
  'Crucifixo Reto Halteres': 'https://www.youtube.com/watch?v=ViDnPVHZh9g',
  'Crucifixo Inclinado Halteres': 'https://www.youtube.com/watch?v=Q6AG6lc1CFw',
  'Crucifixo Declinado Halteres': 'https://www.youtube.com/watch?v=TzNddpnTrZA',
  'Cross-Over Polia Alta': 'https://www.youtube.com/watch?v=JqmOvA2-ndk',
  'Cross-Over Polia Média': 'https://www.youtube.com/watch?v=tIG_1WCEbnc',
  'Cross-Over Polia Baixa': 'https://www.youtube.com/watch?v=o5-5Zu2AZ9M',
  'Peck Deck ou Crucifixo Na Máquina': 'https://www.youtube.com/watch?v=jDKk4Jb_M9Q',
  'Flexão De Braço': 'https://www.youtube.com/watch?v=RTG8MG34pp0',
  'Barra Fixa Peg Pronada': 'https://www.youtube.com/watch?v=8zord_m_ruw',
  'Barra Fixa Peg Supinada': 'https://www.youtube.com/watch?v=h2M8Hf1ksWc',
  'Barra Fixa Com Triângulo': 'https://www.youtube.com/watch?v=9qjthX_6hak',
  'Levantamento Terra': 'https://www.youtube.com/watch?v=BWiB2yjQKt8',
  'Puxada Vertical Peg Pronada': 'https://www.youtube.com/watch?v=MFXmnkBMqY8',
  'Puxada Vertical Peg Supinada': 'https://www.youtube.com/watch?v=L46CTweid74',
  'Puxada Vertical Com Triângulo': 'https://www.youtube.com/watch?v=gZ7HuwKcyfs',
  'Remada Curvada Peg Pronada': 'https://www.youtube.com/watch?v=Dx7cV1btND0',
  'Remada Curvada Peg Supinada': 'https://www.youtube.com/watch?v=DiZCr6GW-s4',
  'Remada Curvada Cavalinho': 'https://www.youtube.com/watch?v=9wM70t7DX4Y',
  'Remada Curvada Halteres Peg Pronada': 'https://www.youtube.com/watch?v=aRGBqRGPRqE',
  'Remada Curvada Halteres Peg Supinada': 'https://www.youtube.com/watch?v=2yr6_31use0',
  'Remada Curvada Halteres Peg Neutra': 'https://www.youtube.com/watch?v=w6mbf558TAU',
  'Remada Máquina Peg Pronada': 'https://www.youtube.com/watch?v=iZ6yfBcvPak',
  'Remada Máquina Peg Supinada': 'https://www.youtube.com/watch?v=ZTnvHdpjvuY',
  'Remada Máquina Peg Neutra': 'https://www.youtube.com/watch?v=szuqeRm6sKk',
  'Remada Cross Peg Pronada': 'https://www.youtube.com/watch?v=Oa6Upi2ebr0',
  'Remada Cross Peg Supinada': 'https://www.youtube.com/watch?v=6q1qvnvDAs4',
  'Remada Cross Peg Neutra': 'https://www.youtube.com/watch?v=Z1LgYFS8N5s',
  'Remada Unilateral Peg Pronada': 'https://www.youtube.com/watch?v=jfTfpgE79pM',
  'Remada Unilateral Peg Supinada': 'https://www.youtube.com/watch?v=lGIBJGLic4U',
  'Remada Unilateral Peg Neutra': 'https://www.youtube.com/watch?v=clfDVmgGezA',
  'Pull-Down Barra': 'https://www.youtube.com/watch?v=0szjDNBSxYc',
  'Pull-Down Cross Peg Pronada': 'https://www.youtube.com/watch?v=SPhaw7bBwjE',
  'Pull-Down Cross Peg Supinada': 'https://www.youtube.com/watch?v=DM3GDyEep14',
  'Pull-Down Cross Corda': 'https://www.youtube.com/watch?v=7Y6f457oZSI',
  'Elevação Lateral Halteres': 'https://www.youtube.com/watch?v=DseHtimkQBA',
  'Elevação Lateral Sentado Halteres': 'https://www.youtube.com/watch?v=PbKMr4fk_wU',
  'Elevação Lateral Cross Posterior': 'https://www.youtube.com/watch?v=tHH4dG48_lc',
  'Elevação Lateral Cross Anterior': 'https://www.youtube.com/watch?v=qjh3KkeKfbs',
  'Elevação Lateral Unilateral Banco Inclinado': 'https://www.youtube.com/watch?v=0f1xO7mSV_U',
  'Elevação Frontal Barra Peg Pronada': 'https://www.youtube.com/watch?v=sK_t4U6a_DQ',
  'Elevação Frontal Barra Peg Supinada': 'https://www.youtube.com/watch?v=GC7rAxy2pxU',
  'Elevação Frontal Halteres Peg Pronada': 'https://www.youtube.com/watch?v=Wp45lkLFwpw',
  'Elevação Frontal Halteres Peg Supinada': 'https://www.youtube.com/watch?v=SJ5fZcuHbYg',
  'Elevação Frontal Halteres Peg Neutra': 'https://www.youtube.com/watch?v=muHmyn0_E64',
  'Elevação Frontal Cross Peg Pronada': 'https://www.youtube.com/watch?v=F1RgeS-8OS4',
  'Elevação Frontal Cross Peg Supinada': 'https://www.youtube.com/watch?v=psV6ROVnuGo',
  'Elevação Frontal Cross Corda': 'https://www.youtube.com/watch?v=X9jAVX3GcI8',
  'Elevação Frontal Anilha': 'https://www.youtube.com/watch?v=dtRUMSnyLJw',
  'Elevação Frontal Cruzada': 'https://www.youtube.com/watch?v=0UvVQdT3exw',
  'Crucifixo Inverso Halteres': 'https://www.youtube.com/watch?v=UyVU6tLjU80',
  'Crucifixo Inverso Cross': 'https://www.youtube.com/watch?v=ZUcnj8Zjemw',
  'Desenvolvimento Halteres': 'https://www.youtube.com/watch?v=rFxITNYDHl0',
  'Desenvolvimento Anterior': 'https://www.youtube.com/watch?v=h9QTywPlyLQ',
  'Desenvolvimento Posterior': 'https://www.youtube.com/watch?v=BPcbCbA0K_M',
  'Desenvolvimento Militar': 'https://www.youtube.com/watch?v=iGJKnKoXgdQ',
  'Desenvolvimento Smith': 'https://www.youtube.com/watch?v=9h0Pe8jpO7E',
  'Desenvolvimento Máquina': 'https://www.youtube.com/watch?v=xpGGDgIVJA0',
  'Manguito Rotador Externo Barra': 'https://www.youtube.com/watch?v=1-ih1YfTR3k',
  'Manguito Rotador Externo Halteres': 'https://www.youtube.com/watch?v=ZRSWfh6FkNE',
  'Encolhimento Barra Anterior': 'https://www.youtube.com/watch?v=uQ8D9s3ofzg',
  'Encolhimento Barra Posterior': 'https://www.youtube.com/watch?v=gHUpqu9kTCY',
  'Encolhimento Halteres': 'https://www.youtube.com/watch?v=8lB_k77kniU',
  'Encolhimento Smith Anterior': 'https://www.youtube.com/watch?v=udTNTzyeW6M',
  'Encolhimento Smith Posterior': 'https://www.youtube.com/watch?v=vbpYHwSwolM',
  'Remada Alta Halteres': 'https://www.youtube.com/watch?v=nG0p0euiitY',
  'Remada Alta Barra': 'https://www.youtube.com/watch?v=8D83fNbWfew',
  'Remada Alta Cross': 'https://www.youtube.com/watch?v=NM0cOs8Sbrg',
  'Remada Alta Smith': 'https://www.youtube.com/watch?v=fBdQnSus5-4',
  'Paralelas': 'https://www.youtube.com/watch?v=2AMQ288qQ2M',
  'Mergulho': 'https://www.youtube.com/watch?v=DRXnIj1jr4c',
  'Supino Fechado': 'https://www.youtube.com/watch?v=nfxYDQhVgT8',
  'Rosca Testa Barra Peg Pronada': 'https://www.youtube.com/watch?v=sAZfyF0ABtg',
  'Rosca Testa Barra Peg Supinada': 'https://www.youtube.com/watch?v=jWgzRAk6lFU',
  'Rosca Testa Halteres Peg Supinada': 'https://www.youtube.com/watch?v=v5xJTLn0SE4',
  'Rosca Testa Halteres Peg Neutra': 'https://www.youtube.com/watch?v=BCXtS5E-fuI',
  'Rosca Testa Halteres Peg Pronada': 'https://www.youtube.com/watch?v=X2QqUf4spHQ',
  'Tríceps Pulley Corda': 'https://www.youtube.com/watch?v=yW0U1OQbZd8',
  'Tríceps Pulley Peg Pronada': 'https://www.youtube.com/watch?v=V3E3fRVf0kA',
  'Tríceps Pulley Peg Supinada': 'https://www.youtube.com/watch?v=4WZTiixAtlM',
  'Tríceps Pulley Unilateral Peg Pronada': 'https://www.youtube.com/watch?v=AanTF10-8iY',
  'Tríceps Pulley Unilateral Peg Supinada': 'https://www.youtube.com/watch?v=ZcDCyI-r2xk',
  'Rosca Francesa Anilha': 'https://www.youtube.com/watch?v=KYdDptZzGUU',
  'Rosca Francesa Barra Peg Pronada': 'https://www.youtube.com/watch?v=gi8BdnLgsG4',
  'Rosca Francesa Barra Peg Supinada': 'https://www.youtube.com/watch?v=n0tWbKxWPI4',
  'Rosca Francesa Halteres Peg Neutra': 'https://www.youtube.com/watch?v=WdKUcon92E4',
  'Rosca Francesa Halteres Peg Supinada': 'https://www.youtube.com/watch?v=nrUro4LuT9w',
  'Rosca Francesa Cross Corda': 'https://www.youtube.com/watch?v=MxCqwbToPH8',
  'Tríceps Coice Bilateral Halteres': 'https://www.youtube.com/watch?v=KLwopHtGipU',
  'Tríceps Coice Unilateral Halteres': 'https://www.youtube.com/watch?v=idGKf-AqdNI',
  'Tríceps Coice Unilateral Cross': 'https://www.youtube.com/watch?v=AOsaVJjfF0g',
  'Flexão De Braço Fechada': 'https://www.youtube.com/watch?v=13iILH7aIR0',
  'Rosca Direta Barra Reta ou Barra W': 'https://www.youtube.com/watch?v=_lTtQcOQaso',
  'Rosca Direta Halteres': 'https://www.youtube.com/watch?v=Ebaf7Dp7WBE',
  'Rosca Direta Cross': 'https://www.youtube.com/watch?v=iZ3lgvm6Ja4',
  'Rosca Martelo Barra H': 'https://www.youtube.com/watch?v=2ZsQvsKmoCs',
  'Rosca Martelo Halteres': 'https://www.youtube.com/watch?v=Xzsu1j7ZGzc',
  'Rosca Martelo Corda Cross': 'https://www.youtube.com/watch?v=EaWl7tT_RkY',
  'Rosca Alternada Halteres': 'https://www.youtube.com/watch?v=krxv9NLVO3w',
  'Rosca Alternada Cross-Over': 'https://www.youtube.com/watch?v=T3FipqeOTrY',
  'Rosca Scott Halteres': 'https://www.youtube.com/watch?v=hA7EA-ZZkVo',
  'Rosca Scott Barra ou Barra W': 'https://www.youtube.com/watch?v=tG6khbF_6W0',
  'Rosca Scott Máquina': 'https://www.youtube.com/watch?v=GHR3aiJfboU',
  'Rosca Concentrada': 'https://www.youtube.com/watch?v=6H10Cy-1UzU',
  'Rosca Concentrada Martelo': 'https://www.youtube.com/watch?v=NqXU7MUl3RA',
  'Flexão de Punho Barra Sentado': 'https://www.youtube.com/watch?v=zCZ8MnWTsWk',
  'Extensão de Punho Barra Sentado': 'https://www.youtube.com/watch?v=-mMu5GK-TQ4',
  'Extensão de Punho Barra Em Pé': 'https://www.youtube.com/watch?v=Agm6CbtdycU',
  'Extensão de Punho Cross': 'https://www.youtube.com/watch?v=c_X_Qraf4Uw',
  'Flexão de Punho Cross': 'https://www.youtube.com/watch?v=iibC4idQP9w',
  'Rotacional de Punho': 'https://www.youtube.com/watch?v=ZMev2xXkZ8A',
  'Rosca Inversa Barra': 'https://www.youtube.com/watch?v=akAm42JYAqw',
  'Rosca Inversa Cross': 'https://www.youtube.com/watch?v=DatJs0ptpNw',
  'Rosca Inversa Alternada': 'https://www.youtube.com/watch?v=sakEIAiW3Ok',
  'Flexão de Punho Barra Em Pé': 'https://www.youtube.com/watch?v=cPFbaIO2nG0',
  'Agachamento Livre': 'https://www.youtube.com/watch?v=8oyCSDA8lPw',
  'Agachamento Livre Frontal': 'https://www.youtube.com/watch?v=_8tuQsKyAfA',
  'Agachamento Hack': 'https://www.youtube.com/watch?v=YmVxBUTAasI',
  'Agachamento Smith': 'https://www.youtube.com/watch?v=LTPwK-INi2s',
  'Agachamento Smith Frontal': 'https://www.youtube.com/watch?v=g5ihw4qpYr8',
  'Agachamento Halteres': 'https://www.youtube.com/watch?v=Zo-518i8oYI',
  'Agachamento Adutores': 'https://www.youtube.com/watch?v=q0FePXIU4Og',
  'Passada Barra': 'https://www.youtube.com/watch?v=NS7HNKc20J8',
  'Passada Halteres': 'https://www.youtube.com/watch?v=LuDe9JQ4e8I',
  'Afundos Barra': 'https://www.youtube.com/watch?v=NtvA55QVXNw',
  'Afundos Halteres': 'https://www.youtube.com/watch?v=MMdEQW2OYqQ',
  'Afundos Smith': 'https://www.youtube.com/watch?v=IdAO23b0iLQ',
  'Cadeira Extensora': 'https://www.youtube.com/watch?v=UMgofcSVTys',
  'Mesa Flexora': 'https://www.youtube.com/watch?v=-zhoNlq504E',
  'Cadeira Flexora': 'https://www.youtube.com/watch?v=GzR1m3vVNHA',
  'Flexor Vertical': 'https://www.youtube.com/watch?v=rDQ2azPlf4w',
  'Leg Press': 'https://www.youtube.com/watch?v=OOeIL5cWKhA',
  'Leg Press Adutores': 'https://www.youtube.com/watch?v=zz5zQnPkcVs',
  'Stiff Barra': 'https://www.youtube.com/watch?v=Ls2M9sGwR2A',
  'Stiff Halteres': 'https://www.youtube.com/watch?v=p99VO6uUXf8',
  'Stiff Smith': 'https://www.youtube.com/watch?v=TLgwnIOlSOg',
  'Agachamento Bulgaro Halteres': 'https://www.youtube.com/watch?v=hm3Ar7Vmm3Q',
  'Agachamento Bulgaro Barra': 'https://www.youtube.com/watch?v=o89hufP9eeQ',
  'Cadeira Adutora': 'https://www.youtube.com/watch?v=MEY6-V9B6Jw',
  '4 Apoios Joelho Estendido': 'https://www.youtube.com/watch?v=N_WzWDNu7n8',
  '4 Apoios Joelho Flexionado': 'https://www.youtube.com/watch?v=C-EOKwHAIvI',
  'Glúteos Graviton': 'https://www.youtube.com/watch?v=sUcmv_wCn1E',
  'Glúteos Máquina': 'https://www.youtube.com/watch?v=SWDrdfIyZmg',
  'Glúteos Smith': 'https://www.youtube.com/watch?v=k4oYwS0G_Qo',
  'Glúteos Cross': 'https://www.youtube.com/watch?v=wY7BvHjtOsA',
  'Elevação Pélvica Barra': 'https://www.youtube.com/watch?v=3kG59qFmOCc',
  'Elevação Pélvica Halter': 'https://www.youtube.com/watch?v=triBX5ZSD_M',
  'Elevação Pélvica Anilha': 'https://www.youtube.com/watch?v=s79i2vbh8lk',
  'Elevação Pélvica Smith': 'https://www.youtube.com/watch?v=EpX5bhCfLHM',
  'Cadeira Abdutora': 'https://www.youtube.com/watch?v=FDlK47WC_xs',
  'Gêmeos Em Pé Máquina': 'https://www.youtube.com/watch?v=O2vZCw1tGyU',
  'Gêmeos Em Pé Hack': 'https://www.youtube.com/watch?v=Js9by33SmUA',
  'Gêmeos Em Pé Smith': 'https://www.youtube.com/watch?v=UEVnF8Zie-c',
  'Gêmeos Em Pé Livre': 'https://www.youtube.com/watch?v=LRHNDDZypWM',
  'Gêmeos Sentado Máquina': 'https://www.youtube.com/watch?v=jrXq3m8xiqQ',
  'Gêmeos Sentado Smith': 'https://www.youtube.com/watch?v=Q9FS92bAZSw',
  'Gêmeos Sentado Livre': 'https://www.youtube.com/watch?v=Bsm2_TiK3aI',
  'Gêmeos Leg Press': 'https://www.youtube.com/watch?v=QwVtTeFLZAI',
  'Supra': 'https://www.youtube.com/watch?v=Pc_fo3WFm_I',
  'Infra': 'https://www.youtube.com/watch?v=Y8FYyoV4d8o',
  'Oblíquos': 'https://www.youtube.com/watch?v=7DylVK8jceA',
  'Prancha': 'https://www.youtube.com/watch?v=AB-boevgf8w',
  'Extensão Lombar': 'https://www.youtube.com/watch?v=Vu9vg40C_Ew'
}

export { getVideo }

// // >>> Página buscada:
// // >>> https://www.leandrotwin.com.br/assessoria/listadeexecicios.php
//
// const videos = {}

// document.querySelectorAll('.accordion').forEach((accordion) => {
//   accordion.querySelectorAll('.table-striped tbody tr').forEach((tr) => {
//     const tds = tr.querySelectorAll('td')
//     if (tds.length > 0) {
//       videos[tds[0].textContent.trim()] = tds[1].querySelector('a').textContent.trim()
//     }
//   })
// })

// console.log(JSON.stringify(videos, null, 2))
